FROM debian:latest

RUN apt update -y && apt upgrade -y && \
    apt install build-essential -y && \
    apt install python3 -y && apt install python3-pip -y && \
    apt install vim -y && apt install git -y
#RUN pip install pandas


#RUN apt update -y && apt upgrade -y && apt install vim -y && apt install build-essential && apt install python3 -y && apt install python3-pip -y

#RUN python -m pip install --upgrade pip && pip install pandas